apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-app-config
  namespace: microservice-demo
data:
  FLASK_ENV: "production"
  FLASK_APP: "main.py"
  PORT: "5000"
  HOST: "0.0.0.0"
  # Configuration settings that aren't sensitive
  APP_LOG_LEVEL: "INFO"